name: ci-unit-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os }}-node-v${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['12', '14', '16', '17', '18']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run unit tests
        run: yarn test --coverage --verbose
      - name: Run integration tests
        if: matrix.node == '18'
        run: yarn test:integration
      - name: Run build
        run: yarn build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.node == '17'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/coverage-final.json
          flags: unittests
          name: codecov-spotify-token
          verbose: true
